config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pages/login'
  root to: 'pages#login'

  get 'pages/welcome', to: 'pages#welcome'
  get 'pages/scoreboard', to: 'pages#scoreboard'
  get 'pages/add_ques', to: 'pages#add_ques'
  get 'pages/rate_ques', to: 'pages#rate_ques'
  get '/questions/:id', to: 'questions#show', as: 'question'
  get '/answers/:id' , to: 'answers#show' , as: 'answer'
  get '/questions' , to: 'questions#index' , as: 'questions'
  get 'pages/categories', to: 'pages#categories'
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/questions_completed.rb
class QuestionsCompleted < ApplicationRecord
end

app/models/scorboard.rb
class Scorboard < ApplicationRecord
end

app/models/scoreboard.rb
class Scoreboard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  #before_filter :authenticate_user!, except: [:index, :show]
  #before_filter :set_cache_control_headers, only: [:index, :show]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])
    @body = @answer.body

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to @question }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern
  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      render json: { message: e.message }, status: 404
    end
    rescue_from ActiveRecord::RecordInvalid do |e|
      render json: { message: e.message }, status: 422
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def login
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  #before_filter :authenticate_user!, except: [:index, :show]
  #before_filter :set_cache_control_headers, only: [:index, :show]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.order(:updated_at)

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @questions }
    end
  end

  def next
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end


  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def question_params
      params.require(:question).permit(:body, :image, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/answers/edit.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answers/index.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to answer.id, answer_path(answer) %></td>
        <td><%= link_to answer.body, answer_path(answer) %></td>
        <td><%=l answer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_path(answer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_path(answer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_path,
            :class => 'btn btn-primary' %>

app/views/answers/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => 'New Answer' %></h1>
</div>
<%= render :partial => 'form' %>

app/views/answers/show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @answer.body %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@answer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@answer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/add_ques.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
box-sizing: border-box;
}

/* Style the body */
body {
font-family: Arial, Helvetica, sans-serif;
margin: 0;
}

/* Header/logo Title */
.header {
padding: 40px;
text-align: center;
background: #1abc9c;
color: white;
}

/* Increase the font size of the heading */
.header h1 {
font-size: 40px;
}

/* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
.navbar {
overflow: hidden;
background-color: #333;
position: sticky;
position: -webkit-sticky;
top: 0;
}

/* Style the navigation bar links */
.navbar a {
float: left;
display: block;
color: white;
text-align: center;
padding: 14px 20px;
text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
float: right;
}

/* Change color on hover */
.navbar a:hover {
background-color: #ddd;
color: black;
}

/* Active/current link */
.navbar a.active {
background-color: #666;
color: white;
}

/* Column container */
.row {
display: -ms-flexbox; /* IE10 */
display: flex;
-ms-flex-wrap: wrap; /* IE10 */
flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
-ms-flex: 30%; /* IE10 */
flex: 30%;
background-color: #f1f1f1;
padding: 20px;
}

/* Main column */
.main {
-ms-flex: 70%; /* IE10 */
flex: 70%;
background-color: white;
padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
background-color: #aaa;
width: 100%;
padding: 20px;
}

/* Footer */
.footer {
padding: 20px;
text-align: center;
background: #ddd;
}

/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
.row {
flex-direction: column;
}
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
.navbar a {
float: none;
width: 100%;
}
}
</style>
</head>
<body>

<div class="header">
<h1>Welcome to Trivia game!</h1>
<h2>Your Score: </h2>
</div>

<div class="navbar">
<a href="/pages/welcome" class="active">Home</a>
<a href="/pages/login" class="right">Logout</a>
</div>

<div class="row">
<div class="side">
<div class="fakeimg" style="height:60px;"><a href="/pages/categories">Play trivia</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/pages/scoreboard">View scoreboard</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/pages/add_ques">Add a new question</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/pages/rate_ques">Rate a question</a></div><br>
</div>
<div class="main">
<h2>Add question!</h2>
</div>
</div>
<div class="footer">
<h5>Designed by Rachna</h5>
</div>

</body>
</html>

app/views/pages/categories.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
box-sizing: border-box;
}

/* Style the body */
body {
font-family: Arial, Helvetica, sans-serif;
margin: 0;
}

/* Header/logo Title */
.header {
padding: 40px;
text-align: center;
background: #1abc9c;
color: white;
}

/* Increase the font size of the heading */
.header h1 {
font-size: 40px;
}

/* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
.navbar {
overflow: hidden;
background-color: #333;
position: sticky;
position: -webkit-sticky;
top: 0;
}

/* Style the navigation bar links */
.navbar a {
float: left;
display: block;
color: white;
text-align: center;
padding: 14px 20px;
text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
float: right;
}

/* Change color on hover */
.navbar a:hover {
background-color: #ddd;
color: black;
}

/* Active/current link */
.navbar a.active {
background-color: #666;
color: white;
}

/* Column container */
.row {
display: -ms-flexbox; /* IE10 */
display: flex;
-ms-flex-wrap: wrap; /* IE10 */
flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
-ms-flex: 30%; /* IE10 */
flex: 30%;
background-color: #f1f1f1;
padding: 20px;
}

/* Main column */
.main {
-ms-flex: 70%; /* IE10 */
flex: 70%;
background-color: white;
padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
background-color: #aaa;
width: 100%;
padding: 20px;
}

/* Footer */
.footer {
padding: 20px;
text-align: center;
background: #ddd;
}

/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
.row {
flex-direction: column;
}
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
.navbar a {
float: none;
width: 100%;

}
}
</style>
</head>
<body>

<div class="header">
<h1>Welcome to Trivia game!</h1>
<h2>Your Score: </h2>
</div>

<div class="navbar">
<a href="/pages/welcome" class="active">Home</a>
<a href="/pages/login" class="right">Logout</a>
</div>

<div class="row">
<div class="side">
<div class="fakeimg" style="height:60px;"><a href="/pages/categories">Play trivia</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/pages/scoreboard">View scoreboard</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/pages/add_ques">Add a new question</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/pages/rate_ques">Rate a question</a></div><br>
</div>
<div class="main">
<div class="fakeimg" style="height:60px;"><a href="/questions/3">Movies Questions</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/questions/3">Science Questions</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/questions/3">Politics Questions</a></div><br>
<div class="fakeimg" style="height:60px;"><a href="/questions/3">Paintings Questions</a></div><br>
</div>
</div>

<div class="footer">
<h5>Designed by Rachna</h5>
</div>

</body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
box-sizing: border-box;
}
 
/* Style the body */
body {
font-family: Arial, Helvetica, sans-serif;
margin: 0;
}
 
/* Header/logo Title */
.header {
padding: 80px;
text-align: center;
background: #1abc9c;
color: white;
}
 
/* Increase the font size of the heading */
.header h1 {
font-size: 40px;
}
 
/* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
.navbar {
overflow: hidden;
background-color: #333;
position: sticky;
position: -webkit-sticky;
top: 0;
}
 
/* Style the navigation bar links */
.navbar a {
float: left;
display: block;
color: white;
text-align: center;
padding: 14px 20px;
text-decoration: none;
}
 
/* Right-aligned link */
.navbar a.right {
float: right;
}
 
/* Change color on hover */
.navbar a:hover {
background-color: #ddd;
color: black;
}
 
/* Active/current link */
.navbar a.active {
background-color: #666;
color: white;
}
 
/* Column container */
.row {
display: -ms-flexbox; /* IE10 */
display: flex;
-ms-flex-wrap: wrap; /* IE10 */
flex-wrap: wrap;
}
 
/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
-ms-flex: 30%; /* IE10 */
flex: 30%;
background-color: #f1f1f1;
padding: 20px;
}
 
/* Main column */
.main {
-ms-flex: 70%; /* IE10 */
flex: 70%;
background-color: white;
padding: 20px;
}
 
/* Fake image, just for this example */
.fakeimg {
background-color: #aaa;
width: 100%;
padding: 20px;
}
 
/* Footer */
.footer {
padding: 20px;
text-align: center;
background: #ddd;
}
 
/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
.row {
flex-direction: column;
}
}
 
/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
.navbar a {
float: none;
width: 100%;
}
}
</style>
</head>
<body>
 
<div class="header">
<h1>Welcome to Trivia game!</h1>
<p>A <b>Login!Create!Answer!</b> It's trivia time!!</p>
</div>
 
<div class="navbar">
<a href="#" class="active">Home</a>
<a href="#">Link</a>
<a href="#">Link</a>
<a href="#" class="right">Link</a>
</div>
 
<div class="row">
<div class="side">
<h2>About Me</h2>
<h5>Photo of me:</h5>
<div class="fakeimg" style="height:200px;">Image</div>
<p>Some text about me in culpa qui officia deserunt mollit anim..</p>
<h3>More Text</h3>
<p>Lorem ipsum dolor sit ame.</p>
<div class="fakeimg" style="height:60px;">Image</div><br>
<div class="fakeimg" style="height:60px;">Image</div><br>
<div class="fakeimg" style="height:60px;">Image</div>
</div>
<div class="main">
<h2>TITLE HEADING</h2>
<h5>Title description, Dec 7, 2017</h5>
<div class="fakeimg" style="height:200px;">Image</div>
<p>Some text..</p>
<p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
<br>
<h2>TITLE HEADING</h2>
<h5>Title description, Sep 2, 2017</h5>
<div class="fakeimg" style="height:200px;">Image</div>
<p>Some text..</p>
<p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
</div>
</div>
 
<div class="footer">
<h2>Footer</h2>
</div>
 
</body>
</html>

app/views/pages/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
box-sizing: border-box;
}
 
/* Style the body */
body {
font-family: Arial, Helvetica, sans-serif;
margin: 0;
}
 
/* Header/logo Title */
.header {
padding: 40px;
text-align: center;
background: #1abc9c;
color: white;
}
 
/* Increase the font size of the heading */
.header h1 {
font-size: 40px;
}
 
/* Sticky navbar - toggles between relative and fixed, depending on the scroll position. It is positioned relative until a given offset position is met in the viewport - then it "sticks" in place (like position:fixed). The sticky value is not supported in IE or Edge 15 and earlier versions. However, for these versions the navbar will inherit default position */
.navbar {
overflow: hidden;
background-color: #333;
position: sticky;
position: -webkit-sticky;
top: 0;
}
 
/* Style the navigation bar links */
.navbar a {
float: left;
display: block;
color: white;
text-align: center;
padding: 14px 20px;
text-decoration: none;
}
 
/* Right-aligned link */
.navbar a.right {
float: right;
}
 
/* Change color on hover */
.navbar a:hover {
background-color: #ddd;
color: black;
}
 
/* Active/current link */
.navbar a.active {
background-color: #666;
color: white;
}
 
/* Column container */
.row {
display: -ms-flexbox; /* IE10 */
display: flex;
-ms-flex-wrap: wrap; /* IE10 */
flex-wrap: wrap;
}
 
/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
-ms-flex: 30%; /* IE10 */
flex: 30%;
background-color: #f1f1f1;
padding: 20px;
}
 
/* Main column */
.main {
-ms-flex: 70%; /* IE10 */
flex: 70%;
background-color: white;
padding: 20px;
}
 
/* Fake image, just for this example */
.fakeimg {
background-color: #aaa;
width: 100%;
padding: 20px;
}
 
/* Footer */
.footer {
padding: 20px;
text-align: center;
background: #ddd;
}
 
/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
.row {
flex-direction: column;
}
}
 
/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
.navbar a {
float: none;
width: 100%;

}
}
</style>
</head>
<body>
 
<div class="header">
<h1>Welcome to Trivia game!</h1>
<h2>Login!Create!Answer! It's trivia time!!</h2>
</div>
 
<div class="navbar">
<a href="#" class="active">Home</a>
</div>

<div class="row">
<div class="side">
<div class="fakeimg" style="height:60px;">Login</div><br>
<div style="height:60px;"></div><br>
<div style="height:60px;"></div><br>
<div style="height:60px;"></div>
</div>
<div class="main">
    <label for="uname"><b>Username</b></label><br>
    <input type="text" placeholder="Enter Username" name="uname" required><br><br>

    <label for="psw"><b>Password</b></label><br>
    <input type="password" placeholder="Enter Password" name="psw" required><br><br>

    <div>
    <a href="/pages/welcome" </a>
    <button type="submit">Login</button><br>
    </div>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
</div>
</div><br>

<div class="footer">
<h5>Designed by Rachna</h5>
</div>
 
</body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <div class='control-group'>
    <%= f.label :body, 'Question Text:', :class =>'control-label' %>
    <div class='controls'>
      <%= f.text_field :body, :class => 'input-large' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :image, 'Image:', :class => 'control-label' %>
    <div class='controls'>
      <%=f.file_field :image, :id => 'lefile', :style => 'display:none' %>
      <div class="input-append">
        <input id="photoCover" type="text">
        <a class="btn" onclick="$('input[id=lefile]').click();">Browse</a>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remote_image_url, 'Or Image URL:', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remote_image_url, :class => 'input-large' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/new.html.erb
<div class="page-header">
   <h1><%=t '.title', :default => 'New Question' %></h1>
</div>
<%= render :partial => 'form' %>